version: '3.6'
services:
  frontend:
    restart: always
    command : npm start
    container_name: front
    build: ./react-rentfurlax-capstone/
    image: akashkale/reactjs-app:1.0 
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  backend:
    build: ./DjangoRestApiMongoDB/
    image: akashkale/python-app:1.0
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    links:
      - mongodb
